services:
  datagos_mysql:
    image: mysql:8.0
    container_name: datagos-mysql
    restart: unless-stopped
    ports:
      - 8306:3306
    environment:
      MYSQL_USER: datagos
      MYSQL_PASSWORD: datogs
      MYSQL_ROOT_PASSWORD: datagos
      MYSQL_DATABASE: datagos
      MYSQL_TCP_PORT: 3306
      TZ: 'UTC'
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
      datagos_network:
    volumes:
      - datagos_data:/var/lib/mysql

volumes:
  datagos_data:

networks:
  datagos_network:
